---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: ghcr.io/abatilo/blog:DOCKER_TAG
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  selector:
    app: blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: blog
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: blog
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog
spec:
  dnsNames:
    - aaronbatilo.dev
    - www.aaronbatilo.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: blog-cert
---
apiVersion: "traefik.containo.us/v1alpha1"
kind: "IngressRoute"
metadata:
  name: blog-secure
spec:
  entryPoints: ["websecure"]
  routes:
    - match: "Host(`aaronbatilo.dev`, `www.aaronbatilo.dev`)"
      kind: "Rule"
      middlewares:
        - name: security-headers
          namespace: traefik
      services:
        - name: blog
          port: 80
---
apiVersion: "traefik.containo.us/v1alpha1"
kind: "Middleware"
metadata:
  name: calendar
spec:
  redirectRegex:
    regex: .*
    replacement: https://www.calendarhero.to/aaron
    permanent: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: calendar
spec:
  dnsNames:
    - calendar.aaronbatilo.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: calendar-cert
---
apiVersion: "traefik.containo.us/v1alpha1"
kind: "IngressRoute"
metadata:
  name: calendar
spec:
  entryPoints: ["web", "websecure"]
  routes:
    - match: "Host(`calendar.aaronbatilo.dev`)"
      kind: "Rule"
      middlewares:
        - name: calendar
      services:
        - name: noop@internal
          kind: TraefikService
