---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: blog
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: blog
      containers:
        - name: blog
          image: ghcr.io/abatilo/blog:DOCKER_TAG
          ports:
            - containerPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blog
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blog
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
---
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  selector:
    app: blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: blog
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: blog
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog
spec:
  dnsNames:
    - aaronbatilo.dev
    - www.aaronbatilo.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: blog-cert
---
apiVersion: "traefik.containo.us/v1alpha1"
kind: "IngressRoute"
metadata:
  name: blog-secure
spec:
  entryPoints: ["websecure"]
  tls:
    secretName: blog-cert
  routes:
    - match: "Host(`aaronbatilo.dev`, `www.aaronbatilo.dev`)"
      kind: "Rule"
      middlewares:
        - name: security-headers
          namespace: traefik
      services:
        - name: blog
          port: 80
---
apiVersion: "traefik.containo.us/v1alpha1"
kind: "Middleware"
metadata:
  name: borabora
spec:
  redirectRegex:
    regex: .*
    replacement: https://photos.app.goo.gl/Sbttz9nDzN2SzVYw6
    permanent: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: borabora
spec:
  dnsNames:
    - borabora.aaronbatilo.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: borabora-cert
---
apiVersion: "traefik.containo.us/v1alpha1"
kind: "IngressRoute"
metadata:
  name: borabora
spec:
  entryPoints: ["web", "websecure"]
  tls:
    secretName: borabora-cert
  routes:
    - match: "Host(`borabora.aaronbatilo.dev`)"
      kind: "Rule"
      middlewares:
        - name: borabora
      services:
        - name: noop@internal
          kind: TraefikService
