baseURL = "/"
title = "Aaron Batilo"
theme = "etch"
languageCode = "en-US"

[params]
  description = "The website of someone who owns a light up keyboard"
  dark = "auto"
  highlight = true

[menu]

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
