name: Delete old container images

on:
  workflow_dispatch: {}


jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete 'dev' containers older than a week
        uses: snok/container-retention-policy@v1
        with:
          image-names: blog
          cut-off: A week ago UTC
          account-type: personal
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-at-least: 15
